version: '3'

services:
  app:
    build: .
    ports:
      - 80:80
  
  db:
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  redis:
    image: "redis:alpine"

  rabbitmq:
    image: "rabbitmq:3.8-rc-alpine"